#!/bin/bash

# Script pour exécuter la migration LinkedIn
# Ce script affiche les instructions pour exécuter la migration dans Supabase

echo "=========================================="
echo "Migration LinkedIn - Instructions"
echo "=========================================="
echo ""
echo "La migration SQL est prête dans : prisma/migrations/add_linkedin_fields.sql"
echo ""
echo "Pour l'exécuter :"
echo ""
echo "1. Ouvrez votre dashboard Supabase : https://supabase.com/dashboard"
echo "2. Sélectionnez votre projet"
echo "3. Allez dans 'SQL Editor'"
echo "4. Copiez-collez le contenu du fichier prisma/migrations/add_linkedin_fields.sql"
echo "5. Cliquez sur 'Run'"
echo ""
echo "Ou utilisez psql directement :"
echo "psql \$DATABASE_URL < prisma/migrations/add_linkedin_fields.sql"
echo ""
echo "=========================================="
echo "Vérification après migration :"
echo "=========================================="
echo ""
echo "Après la migration, vérifiez que les champs sont créés :"
echo ""
echo "SELECT column_name, data_type"
echo "FROM information_schema.columns"
echo "WHERE table_name = 'users'"
echo "AND column_name LIKE 'linkedin%';"
echo ""
echo "Vous devriez voir 10 colonnes LinkedIn."
echo ""

